services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=go-test-task-db
    depends_on:
      - postgres_setup

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-test-task-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_setup:
    build:
      context: .
      dockerfile: Dockerfile.setup
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [ "bash", "-c", "migrations/migrate-and-seed.sh"]      

volumes:
  postgres_data:
